import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#8BA889',
    position: 'relative',
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#8BA889',
  },
  profileHeader: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    marginTop: 16,
    marginHorizontal: 16,
    padding: 16,
    shadowColor: '#253528',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignItems: 'center',
    paddingBottom: 24,
  },
  coverImage: {
    height: 80,
    backgroundColor: '#49654E',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  profileImageWrapper: {
    marginTop: 40,
    alignItems: 'center',
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  profileInfo: {
    alignItems: 'center',
    marginTop: 12,
    width: '100%',
  },
  name: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#253528',
    marginBottom: 4,
  },
  headline: {
    fontSize: 16,
    color: '#253528',
    marginBottom: 8,
    textAlign: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  infoIcon: {
    marginRight: 6,
  },
  infoText: {
    fontSize: 14,
    color: '#49654E',
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
    width: '100%',
  },
  primaryButton: {
    backgroundColor: '#253528',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    marginHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  secondaryButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#253528',
    marginHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
  },
  secondaryButtonText: {
    color: '#253528',
    fontWeight: '600',
    fontSize: 14,
  },
  buttonIconSpacing: {
    marginRight: 6,
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    marginTop: 16,
    marginHorizontal: 16,
    padding: 16,
    shadowColor: '#253528',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#253528',
    marginBottom: 12,
  },
  aboutText: {
    fontSize: 14,
    color: '#253528',
    lineHeight: 22,
  },
  experienceItem: {
    flexDirection: 'row',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(73, 101, 78, 0.2)',
  },
  companyLogo: {
    width: 48,
    height: 48,
    borderRadius: 8,
    marginRight: 12,
  },
  experienceContent: {
    flex: 1,
  },
  experienceTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#253528',
    marginBottom: 2,
  },
  companyName: {
    fontSize: 14,
    color: '#49654E',
    marginBottom: 2,
  },
  experienceDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  experienceDuration: {
    fontSize: 12,
    color: '#49654E',
  },
  experienceLocation: {
    fontSize: 12,
    color: '#49654E',
  },
  experienceDescription: {
    fontSize: 13,
    color: '#253528',
    lineHeight: 18,
  },
  educationItem: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  educationLogo: {
    width: 40,
    height: 40,
    borderRadius: 8,
    marginRight: 12,
  },
  educationContent: {
    flex: 1,
  },
  institutionName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#253528',
    marginBottom: 2,
  },
  degree: {
    fontSize: 14,
    color: '#49654E',
    marginBottom: 2,
  },
  educationDuration: {
    fontSize: 12,
    color: '#49654E',
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  skillItem: {
    backgroundColor: 'rgba(73, 101, 78, 0.15)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  skillText: {
    color: '#253528',
    fontSize: 13,
    fontWeight: '500',
  },
  accomplishmentItem: {
    fontSize: 14,
    color: '#253528',
    marginBottom: 10,
    lineHeight: 20,
  },
  recommendationItem: {
    flexDirection: 'row',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(73, 101, 78, 0.2)',
  },
  recommenderImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  recommendationContent: {
    flex: 1,
  },
  recommenderName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#253528',
    marginBottom: 2,
  },
  recommenderTitle: {
    fontSize: 12,
    color: '#49654E',
    marginBottom: 4,
  },
  recommendationText: {
    fontSize: 13,
    color: '#253528',
    fontStyle: 'italic',
    lineHeight: 18,
  },
  navbarWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  navbarSpacing: {
    height: 80, // Add space at the bottom of the scroll view to account for navbar
  },
});